[Service]
Environment=VOICE_BACKEND=paraformer
Environment=PARAFORMER_MODEL_DIR=/root/sherpa_models/paraformer-large-int8
Environment=VOICE_MIN_RECORD_SEC=0.46
Environment=VOICE_MAX_RECORD_SEC=3.20
Environment=VOICE_POST_SILENCE_SEC=0.58
Environment=VOICE_FAST_POST_SILENCE_SEC=0.38
