#!/bin/bash
export DISPLAY=${DISPLAY:-:0}
export VOICE_INPUT_DEVICE=${VOICE_INPUT_DEVICE:-dsnoop:CARD=XFMDPV0018,DEV=0}
export AUDIO_OUTPUT_DEVICE=${AUDIO_OUTPUT_DEVICE:-plughw:CARD=Device,DEV=0}
export VOICE_BACKEND=${VOICE_BACKEND:-paraformer}
export PARAFORMER_MODEL_DIR=${PARAFORMER_MODEL_DIR:-/root/sherpa_models/paraformer-large-int8}
export VOICE_SENSEVOICE_FALLBACK=${VOICE_SENSEVOICE_FALLBACK:-1}
export VOICE_SHERPA_FALLBACK=${VOICE_SHERPA_FALLBACK:-0}
export VOICE_GAIN=${VOICE_GAIN:-3.0}
export VOICE_TRIGGER_PEAK=${VOICE_TRIGGER_PEAK:-0.045}
export VOICE_SILENCE_PEAK=${VOICE_SILENCE_PEAK:-0.026}
export VOICE_MIN_RECORD_SEC=${VOICE_MIN_RECORD_SEC:-0.48}
export VOICE_MAX_RECORD_SEC=${VOICE_MAX_RECORD_SEC:-3.20}
export VOICE_POST_SILENCE_SEC=${VOICE_POST_SILENCE_SEC:-0.58}
export VOICE_PRE_ROLL_FRAMES=${VOICE_PRE_ROLL_FRAMES:-25}
export VOICE_NOISE_TRIGGER_MULT=${VOICE_NOISE_TRIGGER_MULT:-1.25}
export VOICE_NOISE_SILENCE_MULT=${VOICE_NOISE_SILENCE_MULT:-1.05}
export VOICE_MIN_TRIGGER_MARGIN=${VOICE_MIN_TRIGGER_MARGIN:-0.012}
export VOICE_MAX_DYNAMIC_TRIGGER=${VOICE_MAX_DYNAMIC_TRIGGER:-0.22}
export VOICE_MAX_DYNAMIC_SILENCE=${VOICE_MAX_DYNAMIC_SILENCE:-0.14}
export VOICE_COOLDOWN_SEC=${VOICE_COOLDOWN_SEC:-0.05}
cd /root/robot_arm
exec python3 /root/robot_arm/voice_control_app.py
